# Config for the 'air' hot-reload tool
[build]
cmd = "go build -o ./tmp/main ./cmd"  # Adjusted for main.go under /cmd
bin = "tmp/main"
full_bin = "tmp/main"
exclude_dir = ["tmp"]

[log]
level = "debug"
